data:
  train_bs: 4
  train_width: 512 
  train_height: 512
  meta_paths:
    - "./data/VFHQ_example.json"
  sample_margin: 30

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True
  gradient_checkpointing: False 
  max_train_steps: 50000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 1000

base_model_path: './pretrained_weights/sd-image-variations-diffusers'
vae_model_path: './pretrained_weights/sd-vae-ft-mse'
image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
pose_encoder_path: './pretrained_weights/liveportrait/base_models/motion_extractor.pth'

motion_encoder_path: './exp_output/personalive_stage1/motion_encoder-xxxxx.pth'
denoising_unet_path: './exp_output/personalive_stage1/denoising_unet-xxxxx.pth'
reference_unet_path: './exp_output/personalive_stage1/reference_unet-xxxxx.pth'
pose_guider_path: './exp_output/personalive_stage1/pose_guider-xxxxx.pth'

discriminator_path: './pretrained_weights/stylegan2_discriminator_ffhq512.pth'

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
window_size: 10
snr_gamma: 5.0
timesteps_list: [999, 666, 333, 0]

seed: 12580
resume_from_checkpoint: ''
checkpointing_steps: 10000
save_model_epoch_interval: 3
exp_name: 'personalive_stage2'
output_dir: './exp_output'